### ISSUE TITLE
configuration file and hearing-impaired?

### ISSUE THREAD

**Issue by victornoel** [BenoitZugmeyer/addic7ed-cli#32]
Hi,

I added the following in my configuration file:
```
$ cat ~/.config/addic7ed 
[flags]
hearing-impaired = no

[languages]
english
```

And when calling addic7ed with a file as a parameter, while it shows me only the english subtitles, it does show me both HI and non HI subtitles. Is this expect? I would have thought that it would filter the HI subtitles with this configuration...

**Comment by BenoitZugmeyer** [comment]
This is expected: subtitles are never totally filtered out, they are weighted and sorted following the user preferences and the top subtitles are then printed. The `--hearing-impaired` option tells to increase the weight of hearing impaired subtitles, so they will be upper in the list, conversely to the default which is to prefer non-hearing impaired version.

This is useful because if there is only hearing impaired subtitles for an episode, it will let the user chose a subtitle even if he/she prefers non-hearing impaired subtitles.

Same goes for the "release" and "languages" options: that's not a strict filter, it just displays the subtitles that looks the most like the request.

Does this fits your needs? maybe we could increase the weight of this option, so less hearing-impaired subtitles would be printed.

**Comment by victornoel** [comment]
ah ok, sorry, I misinterpreted what the filters would do because the for language, only english was shown.

It's ok like that. I guess we could imagine something like:
```
[flags]
hearing-impaired = [high|low|filter|normal]
```

which would mean either increase weight (w.r.t. normal), decrease, remove them completely, or do nothing (which would be the default).

But I don't really need that, just an idea in light of the current expected behaviour!

Thanks for the explanation, feel free to close the issue, it's good for me :)
